import { Dimensions, Platform, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

// ============================================
// HOME SCREEN STYLES
// ============================================
export const homeStyles = StyleSheet.create({
  bgImage: { flex: 1 },
  overlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.4)" },
  container: { flex: 1 },
  scrollContent: { flexGrow: 1, paddingBottom: 120 },
  authContainer: { flex: 1, backgroundColor: "#FFF" },
  authScroll: {
    alignItems: "center",
    paddingHorizontal: "10%",
    paddingTop: 30,
  },
  logo: { width: width * 0.85, height: width * 0.6, marginBottom: -10 },
  authSub: {
    textAlign: "center",
    color: "#7F8C8D",
    marginBottom: 40,
    fontSize: 16,
  },
  input: {
    width: "100%",
    height: 55,
    backgroundColor: "#F4F7F9",
    borderRadius: 15,
    paddingHorizontal: 20,
    marginBottom: 15,
    fontSize: 16,
    color: "#2C3E50",
    borderWidth: 1,
    borderColor: "#EEE",
  },
  termsRow: { flexDirection: "row", alignItems: "center", marginBottom: 20 },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: "#003366",
    borderRadius: 6,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  termsText: { color: "#7F8C8D", fontSize: 13 },
  termsLink: {
    color: "#003366",
    fontWeight: "bold",
    textDecorationLine: "underline",
  },
  primaryBtn: {
    width: "100%",
    height: 60,
    backgroundColor: "#003366",
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  primaryBtnText: { color: "#FFF", fontWeight: "900" },
  profileHeader: { alignItems: "center", marginTop: 60 },
  avatarWrapper: {
    width: 105,
    height: 105,
    justifyContent: "center",
    alignItems: "center",
  },
  profilePic: { width: 105, height: 105, borderRadius: 52.5 },
  avatarCircle: {
    width: 105,
    height: 105,
    borderRadius: 52.5,
    backgroundColor: "#FFF",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: { fontSize: 44, fontWeight: "900", color: "#003366" },
  cameraIcon: {
    position: "absolute",
    bottom: 5,
    right: 5,
    backgroundColor: "#003366",
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#FFF",
  },
  userName: { fontSize: 34, color: "#FFF", marginTop: 15 },
  dashGrid: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    marginTop: 40,
  },
  dashCard: {
    width: "42%",
    backgroundColor: "rgba(255,255,255,0.9)",
    paddingVertical: 25,
    borderRadius: 25,
    alignItems: "center",
    elevation: 5,
  },
  iconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  cardLabel: { fontWeight: "700", color: "#003366", fontSize: 15 },
  logoutBtn: { alignSelf: "center", marginTop: 60 },
  logoutText: { color: "#FFF", textDecorationLine: "underline" },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.85)",
    justifyContent: "center",
    alignItems: "center",
  },
  legalCard: {
    width: "85%",
    maxHeight: "70%",
    backgroundColor: "#FFF",
    borderRadius: 25,
    padding: 25,
    alignItems: "center",
  },
  legalTitle: { fontSize: 24, color: "#003366", marginBottom: 15 },
  legalScroll: { width: "100%", marginBottom: 15 },
  legalText: { fontSize: 14, color: "#2C3E50", lineHeight: 20 },
  welcomeModalCard: {
    width: "85%",
    backgroundColor: "#FFF",
    borderRadius: 35,
    padding: 30,
    alignItems: "center",
  },
  modalTitle: { fontSize: 26, color: "#003366", marginBottom: 10 },
  modalText: { fontSize: 15, textAlign: "center", marginBottom: 20 },
  dismissBtn: {
    backgroundColor: "#003366",
    paddingVertical: 16,
    borderRadius: 20,
    width: "100%",
    alignItems: "center",
  },
  dismissBtnText: { color: "#FFF", fontWeight: "900" },
  debugResetBtn: {
    position: "absolute",
    top: 50,
    right: 20,
    zIndex: 999,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(231, 76, 60, 0.8)",
    padding: 8,
    borderRadius: 12,
  },
  debugResetText: {
    color: "#FFF",
    fontSize: 10,
    fontWeight: "900",
    marginLeft: 5,
  },
});

// ============================================
// REWARDS SCREEN STYLES
// ============================================
export const rewardsStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F2F2F2", paddingTop: 50 },
  scrollContent: { alignItems: "center", paddingBottom: 150 },
  header: {
    backgroundColor: "#003366",
    width: "100%",
    paddingVertical: 40,
    alignItems: "center",
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  headerTitle: { fontSize: 28, color: "#FFF" },
  headerSub: { fontSize: 15, color: "rgba(255,255,255,0.7)", marginTop: 5 },
  welcomeCard: {
    backgroundColor: "#FFF",
    width: width * 0.9,
    borderRadius: 15,
    padding: 20,
    marginTop: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderLeftWidth: 5,
    borderLeftColor: "#E67E22",
  },
  welcomeInfo: { flexDirection: "row", alignItems: "center" },
  welcomeTitle: { fontWeight: "900", color: "#003366" },
  welcomeSub: { color: "#7F8C8D", fontSize: 12 },
  welcomeBtn: { backgroundColor: "#E67E22", padding: 10, borderRadius: 8 },
  welcomeBtnText: { color: "#FFF", fontWeight: "900", fontSize: 12 },
  cardContainer: {
    backgroundColor: "#FFF",
    width: width * 0.94,
    borderRadius: 25,
    padding: 20,
    marginTop: 20,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#003366",
    textAlign: "center",
    marginBottom: 20,
  },
  eyeRow: { justifyContent: "space-around", marginBottom: 15 },
  eyeWrapper: { width: width * 0.15, height: width * 0.15 },
  emptyEye: {
    width: "100%",
    height: "100%",
    borderRadius: 100,
    backgroundColor: "rgba(0,0,0,0.05)",
    justifyContent: "center",
    alignItems: "center",
    borderStyle: "dashed",
    borderWidth: 1,
    borderColor: "#ccc",
  },
  eyePupilEmpty: {
    width: "30%",
    height: "30%",
    borderRadius: 100,
    backgroundColor: "#eee",
  },
  filledEye: {
    width: "100%",
    height: "100%",
    borderRadius: 100,
    backgroundColor: "#0056b3",
    justifyContent: "center",
    alignItems: "center",
  },
  eyeWhite: {
    width: "60%",
    height: "60%",
    borderRadius: 100,
    backgroundColor: "#FFF",
    justifyContent: "center",
    alignItems: "center",
  },
  eyePupil: {
    width: "45%",
    height: "45%",
    borderRadius: 100,
    backgroundColor: "#00bfff",
  },
  mainBtn: {
    flexDirection: "row",
    width: "90%",
    padding: 18,
    borderRadius: 15,
    marginTop: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  mainBtnText: { color: "#FFF", fontWeight: "900" },
  debugBtn: { marginTop: 20, paddingHorizontal: 20 },
  debugText: {
    color: "#FFF",
    backgroundColor: "rgba(0,0,0,0.3)",
    padding: 8,
    borderRadius: 5,
    fontSize: 11,
    fontWeight: "600",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.8)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#FFF",
    width: "80%",
    padding: 30,
    borderRadius: 25,
    alignItems: "center",
  },
  closeBtn: { alignSelf: "flex-end" },
  modalTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: "#003366",
    marginBottom: 20,
  },
  finishBtn: {
    marginTop: 20,
    backgroundColor: "#003366",
    padding: 15,
    borderRadius: 12,
    width: "100%",
    alignItems: "center",
  },
  finishBtnText: { color: "#FFF", fontWeight: "900" },
  blogHandleArea: { alignItems: "center", paddingBottom: 5 },
  blogHandleText: {
    color: "#FFF",
    fontSize: 10,
    fontWeight: "800",
    marginTop: 2,
  },
  blogScrollContent: { padding: 20, paddingBottom: 50 },
  blogSectionTitle: { color: "#FFF", fontSize: 24, marginBottom: 20 },
  postCard: {
    backgroundColor: "#1A1A1A",
    borderRadius: 15,
    padding: 15,
    marginBottom: 20,
  },
  postTitle: {
    color: "#FFF",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 12,
  },
  videoWrapper: {
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "#000",
    width: "100%",
  },
  postText: { color: "#AAA", marginTop: 12, lineHeight: 20 },
});

// ============================================
// LOCATIONS SCREEN STYLES
// ============================================
export const locationsStyles = StyleSheet.create({
  container: { flex: 1 },
  map: { ...StyleSheet.absoluteFillObject },
  markerContainer: {
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  overlayTop: {
    position: "absolute",
    top: Platform.OS === "ios" ? 50 : 30,
    width: "100%",
    alignItems: "center",
  },
  tabBar: {
    flexDirection: "row",
    backgroundColor: "#FFF",
    borderRadius: 12,
    padding: 4,
    elevation: 5,
  },
  tab: {
    paddingHorizontal: 25,
    paddingVertical: 10,
    borderRadius: 10,
    minWidth: 140,
    alignItems: "center",
  },
  activeTab: { backgroundColor: "#003366" },
  inactiveTab: { backgroundColor: "transparent" },
  tabText: { fontWeight: "800", fontSize: 13 },
  activeTabText: { color: "#FFF" },
  inactiveTabText: { color: "#555" },
  overlayBottom: { position: "absolute", width: "100%", paddingHorizontal: 16 },
  card: {
    backgroundColor: "#FFF",
    borderRadius: 24,
    padding: 20,
    elevation: 10,
    shadowOpacity: 0.15,
  },
  branchName: {
    fontSize: 22,
    fontWeight: "900",
    color: "#003366",
    marginBottom: 2,
  },
  statusOpen: {
    color: "#27ae60",
    fontWeight: "bold",
    fontSize: 11,
    textTransform: "uppercase",
    marginBottom: 12,
  },
  statusWeekend: {
    color: "#e67e22",
    fontWeight: "bold",
    fontSize: 11,
    textTransform: "uppercase",
    marginBottom: 12,
  },
  infoRow: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
  infoText: {
    fontSize: 14,
    color: "#444",
    marginLeft: 10,
    flexShrink: 1,
    fontWeight: "500",
  },
  buttonContainer: { marginTop: 15 },
  fullButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: 14,
    width: "100%",
    marginBottom: 10,
  },
  directionsButton: { backgroundColor: "#7B8DFF" },
  callButton: { backgroundColor: "#003366", marginBottom: 0 },
  buttonText: {
    color: "#fff",
    fontWeight: "bold",
    marginLeft: 10,
    fontSize: 16,
  },
});

// ============================================
// EXPLORE (MENU) SCREEN STYLES
// ============================================
export const exploreStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F0F4F9" },
  headerContainer: {
    paddingTop: Platform.OS === "android" ? 40 : 10,
    backgroundColor: "#002347",
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    paddingBottom: 25,
    alignItems: "center",
    elevation: 10,
  },
  mainTitle: {
    fontSize: 34,
    color: "#FFFFFF",
    marginBottom: 8,
    letterSpacing: 4,
    fontWeight: "700",
  },
  headerSubtitle: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.8)",
    marginBottom: 15,
    letterSpacing: 2,
  },
  categoryPickerButton: {
    flexDirection: "row",
    backgroundColor: "rgba(255,255,255,0.15)",
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.25)",
  },
  categoryPickerText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 11,
    letterSpacing: 1.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  modalContent: {
    height: "70%",
    backgroundColor: "#FFF",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 25,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#EEE",
    paddingBottom: 15,
  },
  modalTitle: { fontSize: 28, color: "#003366" },
  modalItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: "#F5F5F5",
  },
  modalItemText: { fontSize: 17, fontWeight: "600", color: "#2C3E50" },
  listPadding: { paddingBottom: 100 },
  sectionHeaderContainer: {
    backgroundColor: "#F0F4F9",
    paddingVertical: 15,
    paddingHorizontal: 20,
  },
  sectionHeader: {
    fontSize: 18,
    backgroundColor: "#003366",
    color: "#FFFFFF",
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignSelf: "flex-start",
    borderRadius: 10,
    fontWeight: "700",
    letterSpacing: 2,
  },
  menuCard: {
    backgroundColor: "#FFFFFF",
    marginHorizontal: 15,
    marginVertical: 10,
    borderRadius: 15,
    padding: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    elevation: 2,
    borderLeftWidth: 4,
    borderLeftColor: "#003366",
  },
  textContainer: { flex: 1, paddingRight: 10 },
  itemName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#002347",
    marginBottom: 4,
  },
  itemDesc: {
    fontSize: 12,
    color: "#666666",
    lineHeight: 16,
    marginBottom: 8,
    fontStyle: "italic",
  },
  itemPrice: { fontSize: 15, fontWeight: "800", color: "#003366" },
  imageContainer: {
    width: width * 0.22,
    aspectRatio: 1,
    borderRadius: 15,
    overflow: "hidden",
    backgroundColor: "#F0F4F8",
  },
  foodImage: { width: "100%", height: "100%" },
});

// ============================================
// MODAL SCREEN STYLES
// ============================================
export const modalStyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  link: {
    marginTop: 15,
    paddingVertical: 15,
  },
});
